### ISSUE TITLE
Always output log in console

### ISSUE THREAD

**Issue by lesliechueng1996** [leisim/logger#30]
I added a logger dependency to a project and every time I start it will print the previously generated log after "Running Gradle task 'assembleDebug' ...". Even after I create a new flutter project, the log will still be printed.

**Comment by haarts** [comment]
That's... really odd. Could you tell us the exact steps to reproduce?

Also try the master version of the project. A change was made to the buffering mechanism. Pointing to master in the pubspec.yaml works like this:
```
  logger:
    git:
      url: git://github.com/leisim/logger.git
      ref: d8a9cd7e1ee4556bf5c659cdd4b8eb40f599b6e6

```
